
exports.up = function(knex, Promise) {
    return Promise.all([
      knex('clinics').insert(
        /*Start of array of data*/
     [
    {
        "id": "1",
        "regional_director": "6",
        "email1": "",
        "name": "Bay Cities Animal Hospital",
        "conversion_date": "2016-06-13",
        "type": "1",
        "pms": "Infinity",
        "accounting_number": "80518",
        "clinic_code": "BAYC",
        "address": "3001 New Street",
        "city": "Burlington",
        "province": "ON",
        "postal": "L7R 1K3",
        "phone1": "905-639-5414",
        "phone2": "905-639-9173",
        "clinic_manager": "46",
        "medical_director": "72"
    },
    {
        "id": "2",
        "regional_director": "3",
        "email1": "",
        "name": "Mt. Pleasant- Davisville Veterinary Hospital",
        "conversion_date": "2016-08-15",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80523",
        "clinic_code": "MTPL",
        "address": "745 Mount Pleasant Rd",
        "city": "Toronto",
        "province": "ON",
        "postal": "M4S 2N4",
        "phone1": "416-481-7387",
        "phone2": "416-481-9872",
        "clinic_manager": "13",
        "medical_director": "73"
    },
    {
        "id": "3",
        "regional_director": "2",
        "email1": "",
        "name": "Varsity Veterinary Clinic",
        "conversion_date": "2016-04-18",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80105",
        "clinic_code": "VARS",
        "address": "107, 4625 Varsity Drive NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3A 0Z9",
        "phone1": "403-247-3617",
        "phone2": "403-288-5756",
        "clinic_manager": "35",
        "medical_director": "74"
    },
    {
        "id": "4",
        "regional_director": "2",
        "email1": "dalhousieveterinaryclinic@gmail.com",
        "name": "Dalhousie Station Veterinary Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80121",
        "clinic_code": "DALH",
        "address": "405, 5005 Dalhousie Road NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3A 5R8",
        "phone1": "403-284-2265",
        "phone2": "403-289-2929",
        "clinic_manager": "64",
        "medical_director": "75"
    },
    {
        "id": "5",
        "regional_director": "11",
        "email1": "",
        "name": "Mayfield Veterinary Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80113",
        "clinic_code": "MFLD",
        "address": "16808-106 Avenue ",
        "city": "Edmonton",
        "province": "AB",
        "postal": "T5P 4Z3",
        "phone1": "780-451-3465",
        "phone2": "780-451-3512",
        "clinic_manager": "51",
        "medical_director": "76"
    },
    {
        "id": "6",
        "regional_director": "2",
        "email1": "",
        "name": "Coach Hill Veterinary Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80118",
        "clinic_code": "COCH",
        "address": "6424 Old Banff Coach Road SW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3H 2H3",
        "phone1": "403-246-8418  ",
        "phone2": "403-246-8361",
        "clinic_manager": "64",
        "medical_director": "77"
    },
    {
        "id": "7",
        "regional_director": "6",
        "email1": "",
        "name": "Kingsway Animal Hospital",
        "conversion_date": "2016-06-27",
        "type": "1",
        "pms": "Vetware",
        "accounting_number": "80501",
        "clinic_code": "KWAY",
        "address": "1770 King Street East",
        "city": "Hamilton",
        "province": "ON",
        "postal": "L8K 1V7",
        "phone1": "905-547-1206",
        "phone2": "905-547-0889",
        "clinic_manager": "60",
        "medical_director": "78"
    },
    {
        "id": "8",
        "regional_director": "2",
        "email1": "",
        "name": "Royal Oak Veterinary Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80109",
        "clinic_code": "ROYO",
        "address": "180, 8888 Country Hills Blvd. NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3G 5T4",
        "phone1": "403-208-0847",
        "phone2": "403-208-0870",
        "clinic_manager": "43",
        "medical_director": "79"
    },
    {
        "id": "9",
        "regional_director": "12",
        "email1": "",
        "name": "Northdale Animal Hospital ",
        "conversion_date": "2016-07-18",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80505",
        "clinic_code": "NDAL",
        "address": "1096 Adelaide Street N",
        "city": "London",
        "province": "ON",
        "postal": "N5Y 2N1",
        "phone1": "519-645-8787",
        "phone2": "519-645-8788",
        "clinic_manager": "44",
        "medical_director": "80"
    },
    {
        "id": "10",
        "regional_director": "2",
        "email1": "",
        "name": "Country Hills Veterinary Clinic",
        "conversion_date": "2016-04-25",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80106",
        "clinic_code": "CTRY",
        "address": "214, 5149 Country Hills Blvd. NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3A 5K8",
        "phone1": "403-547-3388",
        "phone2": "403-241-2550",
        "clinic_manager": "35",
        "medical_director": "81"
    },
    {
        "id": "11",
        "regional_director": "1",
        "email1": "",
        "name": "Beardall Animal Hospital",
        "conversion_date": "2017-01-23",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80517",
        "clinic_code": "BDLL",
        "address": "393 Bath Road",
        "city": "Kingston",
        "province": "ON",
        "postal": "K7M 7C9",
        "phone1": "613-544-6336",
        "phone2": "613-544-7860",
        "clinic_manager": "48",
        "medical_director": "82"
    },
    {
        "id": "12",
        "regional_director": "1",
        "email1": "",
        "name": "Bayview Animal Hospital",
        "conversion_date": "2017-01-16",
        "type": "1",
        "pms": "ImproMed Infinity",
        "accounting_number": "80513",
        "clinic_code": "BVAH",
        "address": "Hampton Park Plaza, 1407 Carling Avenue",
        "city": "Ottawa",
        "province": "ON",
        "postal": "K1Z 7L6",
        "phone1": "613-728- 5852",
        "phone2": "613-728-1665",
        "clinic_manager": "42",
        "medical_director": "83"
    },
    {
        "id": "13",
        "regional_director": "11",
        "email1": "",
        "name": "Calgary Trail Pet Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80128",
        "clinic_code": "CTED",
        "address": "810, 3803 Calgary Trail Northwest",
        "city": "Edmonton",
        "province": "AB",
        "postal": "T6J 5M8",
        "phone1": "780-431-0140",
        "phone2": "780-439-7020",
        "clinic_manager": "18",
        "medical_director": "84"
    },
    {
        "id": "14",
        "regional_director": "10",
        "email1": "",
        "name": "MacEwan Veterinary Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80103",
        "clinic_code": "MACE",
        "address": "9, 16 MacEwan Drive NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3K 2P2",
        "phone1": "403-295-1929",
        "phone2": "403-295-1984",
        "clinic_manager": "70",
        "medical_director": "85"
    },
    {
        "id": "15",
        "regional_director": "5",
        "email1": "bookerl@carecentre.ca",
        "name": "Calgary Animal Referral & Emergency Centre (CARE)",
        "conversion_date": "2020-01-01",
        "type": "2",
        "pms": "Cornerstone",
        "accounting_number": "80108",
        "clinic_code": "CARE",
        "address": "7140 12 Street SE ",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2H 2Y4",
        "phone1": "403-520-8387",
        "phone2": "403-692-4350",
        "clinic_manager": "26",
        "medical_director": "86"
    },
    {
        "id": "16",
        "regional_director": "11",
        "email1": "",
        "name": "Guardian Veterinary Centre",
        "conversion_date": "2020-01-01",
        "type": "2",
        "pms": "DVMax",
        "accounting_number": "80124",
        "clinic_code": "GVCN",
        "address": "5620-99 Street",
        "city": "Edmonton",
        "province": "AB",
        "postal": "T6E 1V2",
        "phone1": "780-436-5880",
        "phone2": "780-436-6222",
        "clinic_manager": "62",
        "medical_director": "87"
    },
    {
        "id": "17",
        "regional_director": "12",
        "email1": "",
        "name": "Masonville Animal Hospital",
        "conversion_date": "2016-11-07",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80506",
        "clinic_code": "MVLL",
        "address": "101 Fanshawe Park E",
        "city": "London",
        "province": "ON",
        "postal": "N5X 3V9",
        "phone1": "519-660-1770",
        "phone2": "519-660-3562",
        "clinic_manager": "59",
        "medical_director": "88"
    },
    {
        "id": "18",
        "regional_director": "4",
        "email1": "",
        "name": "Western Veterinary Specialist & Emergency Centre",
        "conversion_date": "2020-01-01",
        "type": "2",
        "pms": "AIS",
        "accounting_number": "80120",
        "clinic_code": "WVSP",
        "address": "1802 10 Avenue SW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3C 0J8",
        "phone1": "403-770-1340",
        "phone2": "403-770-1344",
        "clinic_manager": "4",
        "medical_director": "89"
    },
    {
        "id": "19",
        "regional_director": "6",
        "email1": "",
        "name": "Barrie Veterinary Hospital",
        "conversion_date": "2016-10-17",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80502",
        "clinic_code": "BRRE",
        "address": "200 Bayfield Street ",
        "city": "Barrie",
        "province": "ON",
        "postal": "L4M 3B6",
        "phone1": "705-728-4545",
        "phone2": "705-728-8556",
        "clinic_manager": "50",
        "medical_director": "90"
    },
    {
        "id": "20",
        "regional_director": "10",
        "email1": "",
        "name": "Marlborough Veterinary Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "DVMax",
        "accounting_number": "80115",
        "clinic_code": "MARL",
        "address": "186, 1440 52 Street NE",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2A 4T8",
        "phone1": "403-273-4664",
        "phone2": "403-273-0421",
        "clinic_manager": "66",
        "medical_director": "91"
    },
    {
        "id": "21",
        "regional_director": "10",
        "email1": "",
        "name": "Riverbend Animal Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "DVMax",
        "accounting_number": "80117",
        "clinic_code": "RBND",
        "address": "354, 8338 18 Street SE",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2C 4E4",
        "phone1": "403-279-8747",
        "phone2": "403-279-8773",
        "clinic_manager": "66",
        "medical_director": "91"
    },
    {
        "id": "22",
        "regional_director": "3",
        "email1": "",
        "name": "Pet Vet Morningside Pet Hospital",
        "conversion_date": "2016-08-22",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80532",
        "clinic_code": "MORN",
        "address": "4560 Kingston Rd",
        "city": "Scarborough",
        "province": "ON",
        "postal": "M1E 2P2",
        "phone1": "416-284-9205",
        "phone2": "416-284-6532",
        "clinic_manager": "17",
        "medical_director": "93"
    },
    {
        "id": "23",
        "regional_director": "3",
        "email1": "",
        "name": "Pet Vet Credit Valley Pet Hospital",
        "conversion_date": "2016-09-12",
        "type": "2",
        "pms": "Cornerstone",
        "accounting_number": "80529",
        "clinic_code": "CRED",
        "address": "6515 Missisauga Rd",
        "city": "Mississauga",
        "province": "ON",
        "postal": "L5N 1A6",
        "phone1": "905-826-1881",
        "phone2": "905-826-7442",
        "clinic_manager": "25",
        "medical_director": "93"
    },
    {
        "id": "24",
        "regional_director": "12",
        "email1": "",
        "name": "Pet Vet Lakeshore Pet Hospital",
        "conversion_date": "2016-10-24",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80531",
        "clinic_code": "LAKE",
        "address": "872 Lakeshore Rd East",
        "city": "Mississauga",
        "province": "ON",
        "postal": "L5E 1E1",
        "phone1": "905-278-4580",
        "phone2": "905-278-5838",
        "clinic_manager": "52",
        "medical_director": "93"
    },
    {
        "id": "25",
        "regional_director": "6",
        "email1": "",
        "name": "Pet Vet Eastside Pet Hospital",
        "conversion_date": "2016-10-03",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80530",
        "clinic_code": "EAST",
        "address": "111 #8 Highway",
        "city": "Stoney Creek",
        "province": "ON",
        "postal": "L8G 1C1",
        "phone1": "905-662-6719",
        "phone2": "905-662-6719",
        "clinic_manager": "60",
        "medical_director": "93"
    },
    {
        "id": "26",
        "regional_director": "1",
        "email1": "management@bellnet.ca",
        "name": "Bells Corners Animal Hospital",
        "conversion_date": "2016-11-21",
        "type": "1",
        "pms": "ImproMed Infinity",
        "accounting_number": "80516",
        "clinic_code": "BELL",
        "address": "Unit 27B, 2194 Robertson Road",
        "city": "Nepean",
        "province": "ON",
        "postal": "K2H 9J5",
        "phone1": "613-820-1641",
        "phone2": "613-820-7131",
        "clinic_manager": "24",
        "medical_director": "97"
    },
    {
        "id": "27",
        "regional_director": "2",
        "email1": "",
        "name": "17th Avenue Animal Hospital",
        "conversion_date": "2016-05-02",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80110",
        "clinic_code": "17TH",
        "address": "233 17 Avenue SW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2S 0A4",
        "phone1": "403-228-4165",
        "phone2": "403-228-5047",
        "clinic_manager": "49",
        "medical_director": "98"
    },
    {
        "id": "28",
        "regional_director": "9",
        "email1": "",
        "name": "Alta Vista Animal Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "ImproMed Infinity",
        "accounting_number": "80512",
        "clinic_code": "AVAH",
        "address": "2616 Bank Street",
        "city": "Ottawa",
        "province": "ON",
        "postal": "K1T 1M9",
        "phone1": "613-731- 6851",
        "phone2": "613- 731-2315",
        "clinic_manager": "40",
        "medical_director": "99"
    },
    {
        "id": "29",
        "regional_director": "6",
        "email1": "",
        "name": "Westside Animal Hospital",
        "conversion_date": "2016-08-08",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80510",
        "clinic_code": "WSDE",
        "address": "Unit 60, 2700 Dufferin Street",
        "city": "Toronto",
        "province": "ON",
        "postal": "M6B 4J3",
        "phone1": "416-783-4285",
        "phone2": "416-787-0281",
        "clinic_manager": "16",
        "medical_director": "100"
    },
    {
        "id": "30",
        "regional_director": "2",
        "email1": "",
        "name": "Shawnessy South Pet Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80111",
        "clinic_code": "SHAW",
        "address": "144, 70 Shawville Blvd. SW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2Y 2Z3",
        "phone1": "403-254-5900",
        "phone2": "403-254-5903",
        "clinic_manager": "28",
        "medical_director": "101"
    },
    {
        "id": "31",
        "regional_director": "6",
        "email1": "",
        "name": "Burlington Animal Hospital ",
        "conversion_date": "2016-06-06",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80503",
        "clinic_code": "BRLT",
        "address": "1231 Guelph Line",
        "city": "Burlington",
        "province": "ON",
        "postal": "L7P 2T1",
        "phone1": "905-335-3515",
        "phone2": "905-335-3656",
        "clinic_manager": "46",
        "medical_director": "102"
    },
    {
        "id": "32",
        "regional_director": "3",
        "email1": "",
        "name": "MacKay Animal Clinic",
        "conversion_date": "2016-06-20",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80522",
        "clinic_code": "MKAC",
        "address": "421 Dundas St. E",
        "city": "Whitby",
        "province": "ON",
        "postal": "L1N 2J2",
        "phone1": "905-668-8861",
        "phone2": "905-668-4740",
        "clinic_manager": "20",
        "medical_director": "103"
    },
    {
        "id": "33",
        "regional_director": "10",
        "email1": "",
        "name": "Forest Lawn Veterinary Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "DVMax",
        "accounting_number": "80114",
        "clinic_code": "FLWN",
        "address": "2002 36 Street SE",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2B 0X8",
        "phone1": "403-272-0115",
        "phone2": "403-569-0321",
        "clinic_manager": "66",
        "medical_director": "104"
    },
    {
        "id": "34",
        "regional_director": "12",
        "email1": "",
        "name": "Blue Cross Animal Hospital",
        "conversion_date": "2016-11-14",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80507",
        "clinic_code": "BCRX",
        "address": "1438 London Road",
        "city": "Sarnia",
        "province": "ON",
        "postal": "N7S 1P7",
        "phone1": "519-542-1255",
        "phone2": "519-542-1259",
        "clinic_manager": "32",
        "medical_director": "105"
    },
    {
        "id": "35",
        "regional_director": "12",
        "email1": "",
        "name": "Corunna Veterinary Services",
        "conversion_date": "2016-11-14",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80508",
        "clinic_code": "CRNA",
        "address": "197 Hill Street",
        "city": "Corunna",
        "province": "ON",
        "postal": "N0N 1G0",
        "phone1": "519-862-4244",
        "phone2": "519-862-4254",
        "clinic_manager": "32",
        "medical_director": "105"
    },
    {
        "id": "36",
        "regional_director": "12",
        "email1": "",
        "name": "Petrolia Veterinary Services",
        "conversion_date": "2016-11-14",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80509",
        "clinic_code": "PTRL",
        "address": "4247 Oil Heritage",
        "city": "Petrolia",
        "province": "ON",
        "postal": "N0N 1R0",
        "phone1": "519-862-4244",
        "phone2": "519-882-3872",
        "clinic_manager": "32",
        "medical_director": "105"
    },
    {
        "id": "37",
        "regional_director": "7",
        "email1": "",
        "name": "404 Veterinary Emergency + Referral Hospital ",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80527",
        "clinic_code": "404V",
        "address": "510 Harry Walker Parkway South",
        "city": "Newmarket",
        "province": "ON",
        "postal": "L3Y 0B3",
        "phone1": "905-953-1933",
        "phone2": "905-953-8845",
        "clinic_manager": "27",
        "medical_director": "108"
    },
    {
        "id": "38",
        "regional_director": "1",
        "email1": "",
        "name": "Ottawa Veterinary Hospital",
        "conversion_date": "2020-01-01",
        "type": "3",
        "pms": "ImproMed Infinity",
        "accounting_number": "80515",
        "clinic_code": "OVEM",
        "address": "900 Boyd Avenue",
        "city": "Ottawa",
        "province": "ON",
        "postal": "K2A 2E3",
        "phone1": "613-725-1182",
        "phone2": "613-725-5656",
        "clinic_manager": "71",
        "medical_director": "109"
    },
    {
        "id": "39",
        "regional_director": "3",
        "email1": "",
        "name": "Willowdale Animal Hospital",
        "conversion_date": "2016-07-25",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80533",
        "clinic_code": "WILL",
        "address": "256 Sheppard Avenue West",
        "city": "Toronto",
        "province": "ON",
        "postal": "M2N 1N3",
        "phone1": "416-222-5409",
        "phone2": "",
        "clinic_manager": "37",
        "medical_director": "110"
    },
    {
        "id": "40",
        "regional_director": "2",
        "email1": "",
        "name": "Crowfoot Veterinary Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80119",
        "clinic_code": "CROW",
        "address": "211, 150 Crowfoot Cresc NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3G 3T2   ",
        "phone1": "403- 241-8944  ",
        "phone2": "403- 547-1903",
        "clinic_manager": "41",
        "medical_director": "111"
    },
    {
        "id": "41",
        "regional_director": "12",
        "email1": "",
        "name": "Lexington Rd. Animal Hospital",
        "conversion_date": "2016-08-29",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80528",
        "clinic_code": "LEXI",
        "address": "135 Lexington Court",
        "city": "Waterloo",
        "province": "ON",
        "postal": "N2J 4R1",
        "phone1": "519-746-4440",
        "phone2": "519-746-2351",
        "clinic_manager": "21",
        "medical_director": "112"
    },
    {
        "id": "42",
        "regional_director": "10",
        "email1": "",
        "name": "Harvest Hills Veterinary Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80104",
        "clinic_code": "HARV",
        "address": "711, 500 Country Hills Blvd. NE ",
        "city": "Calgary",
        "province": "AB",
        "postal": "T3K 4Y7",
        "phone1": "403-226-5522",
        "phone2": "403-226-5602",
        "clinic_manager": "38",
        "medical_director": "113"
    },
    {
        "id": "43",
        "regional_director": "6",
        "email1": "",
        "name": "Birchmount Veterinary Clinic",
        "conversion_date": "2016-10-31",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80500",
        "clinic_code": "BRCH",
        "address": "1563 Birchmount Road ",
        "city": "Scarborough",
        "province": "ON",
        "postal": "M1P 2H4",
        "phone1": "416-752-6048",
        "phone2": "416-757-7083",
        "clinic_manager": "63",
        "medical_director": "114"
    },
    {
        "id": "44",
        "regional_director": "3",
        "email1": "",
        "name": "Secord Animal Hospital",
        "conversion_date": "2016-09-26",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80525",
        "clinic_code": "SECA",
        "address": "3271 Yonge St",
        "city": "Toronto",
        "province": "ON",
        "postal": "M4N 2L8",
        "phone1": "416-486-1700",
        "phone2": "416-486-1795",
        "clinic_manager": "56",
        "medical_director": "115"
    },
    {
        "id": "45",
        "regional_director": "10",
        "email1": "",
        "name": "McKenzie Towne Animal Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "DVMax",
        "accounting_number": "80116",
        "clinic_code": "MTWN",
        "address": "40 High Street SE ",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2Z 3T8",
        "phone1": "403-257-6105",
        "phone2": "403-257-6108",
        "clinic_manager": "66",
        "medical_director": "116"
    },
    {
        "id": "46",
        "regional_director": "1",
        "email1": "",
        "name": "Pretoria Pet Hospital",
        "conversion_date": "2016-12-12",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80514",
        "clinic_code": "PRET",
        "address": "16 Pretoria Avenue",
        "city": "Ottawa",
        "province": "ON",
        "postal": "K1S 1W7",
        "phone1": "613-565-0588",
        "phone2": "613-565-6678",
        "clinic_manager": "53",
        "medical_director": "117"
    },
    {
        "id": "47",
        "regional_director": "11",
        "email1": "",
        "name": "Riverbend Veterinary Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Practice Vantage",
        "accounting_number": "80126",
        "clinic_code": "RVED",
        "address": "5611 Riverbend Road",
        "city": "Edmonton",
        "province": "AB",
        "postal": "T6H 5K4",
        "phone1": "780-437-0039",
        "phone2": "780-438-8366",
        "clinic_manager": "58",
        "medical_director": "118"
    },
    {
        "id": "48",
        "regional_director": "11",
        "email1": "",
        "name": "Capital City Animal Hospital ",
        "conversion_date": "2020-01-01",
        "type": "3",
        "pms": "DVMax",
        "accounting_number": "80123",
        "clinic_code": "EVEC",
        "address": "11104-102 Avenue",
        "city": "Edmonton",
        "province": "AB",
        "postal": "T5K 2H4",
        "phone1": "780-433-9505",
        "phone2": "780-439-2787",
        "clinic_manager": "23",
        "medical_director": "119"
    },
    {
        "id": "49",
        "regional_director": "1",
        "email1": "",
        "name": "Blair Animal Hospital",
        "conversion_date": "2016-11-28",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80520",
        "clinic_code": "BANH",
        "address": "849 Shefford Rd",
        "city": "Gloucester",
        "province": "ON",
        "postal": "K1J 8H9",
        "phone1": "613-746-2443",
        "phone2": "613-746-2006",
        "clinic_manager": "54",
        "medical_director": "120"
    },
    {
        "id": "50",
        "regional_director": "3",
        "email1": "",
        "name": "Rosedale Animal Hospital",
        "conversion_date": "2016-09-19",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80524",
        "clinic_code": "ROSE",
        "address": "1284 Yonge St",
        "city": "Toronto",
        "province": "ON",
        "postal": "M4T 1W5",
        "phone1": "416-964-2298",
        "phone2": "416-964-3982",
        "clinic_manager": "56",
        "medical_director": "121"
    },
    {
        "id": "51",
        "regional_director": "8",
        "email1": "",
        "name": "Calgary North Veterinary Hospital & Emergency Service",
        "conversion_date": "2020-01-01",
        "type": "3",
        "pms": "Cornerstone",
        "accounting_number": "80100",
        "clinic_code": "CNOR",
        "address": "4204-4th Street NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2K 1A2",
        "phone1": "403-277-0135",
        "phone2": "403-230-2335",
        "clinic_manager": "39",
        "medical_director": "122"
    },
    {
        "id": "52",
        "regional_director": "2",
        "email1": "",
        "name": "Hunterhorn Veterinary Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80101",
        "clinic_code": "HUNT",
        "address": "6536 4 Street NE",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2K 6H2",
        "phone1": "403-295-8592",
        "phone2": "403-275-9599",
        "clinic_manager": "2",
        "medical_director": "123"
    },
    {
        "id": "53",
        "regional_director": "2",
        "email1": "",
        "name": "Due South Animal Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Winvet",
        "accounting_number": "80121",
        "clinic_code": "DUSO",
        "address": "16626 McKenzie Lake Blvd. SE",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2Z 1N4",
        "phone1": "403-257-8899",
        "phone2": "403-257-8974",
        "clinic_manager": "29",
        "medical_director": "124"
    },
    {
        "id": "54",
        "regional_director": "1",
        "email1": "",
        "name": "Kanata Animal Hospital",
        "conversion_date": "2016-12-05",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80521",
        "clinic_code": "KANA",
        "address": "440 Hazeldean Rd",
        "city": "Kanata",
        "province": "ON",
        "postal": "K2L 1V2",
        "phone1": "613-836-2848",
        "phone2": "613-836-6974",
        "clinic_manager": "54",
        "medical_director": "125"
    },
    {
        "id": "55",
        "regional_director": "10",
        "email1": "",
        "name": "Calgary Holistic Veterinary Clinic",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Cornerstone",
        "accounting_number": "80107",
        "clinic_code": "CHOL",
        "address": "105, 1640 16 Avenue NW",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2M 0L6",
        "phone1": "403-289-1616",
        "phone2": "403-289-1620",
        "clinic_manager": "31",
        "medical_director": "126"
    },
    {
        "id": "56",
        "regional_director": "2",
        "email1": "",
        "name": "South Trail Pet Hospital",
        "conversion_date": "2020-01-01",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80112",
        "clinic_code": "SOTR",
        "address": "75, 4307 130 Avenue SE",
        "city": "Calgary",
        "province": "AB",
        "postal": "T2Z 3V8",
        "phone1": "403-257-3393",
        "phone2": "403-257-9520",
        "clinic_manager": "29"
    },
    {
        "id": "57",
        "regional_director": "12",
        "email1": "",
        "name": "Matthews Animal Hospital",
        "conversion_date": "2016-07-11",
        "type": "1",
        "pms": "Avimark",
        "accounting_number": "80504",
        "clinic_code": "MATT",
        "address": "1255 Southdale Road E ",
        "city": "London",
        "province": "ON",
        "postal": "N6E 1B3",
        "phone1": "519-681-7575",
        "phone2": "519-681-7725",
        "clinic_manager": "44"
    }
]   
        /*End of insert array*/		
       )
   ]);
};

exports.down = function(knex, Promise) {
    return Promise.all([
      knex('clinics').whereRaw('`id` <= ?', [1000]).del()
  ]);
};
